language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - "pip install -r Bevut/requirements.txt"
    - "pip install flake8"

script:
    - "find Bevut/ -name \\*.py -exec flake8 --max-line-length 120 {} +"
    - "python Bevut/manage.py migrate"
    - "python Bevut/manage.py test"

