# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Lärandeaspekter')),
                ('doneDescription', models.TextField(verbose_name='Kriterier för godkänt')),
                ('wellDoneDescription', models.TextField(help_text='Behövs endast om formuläret har Väl Godkänt', verbose_name='Kriterier för väl godkänt')),
                ('notDoneDescription', models.TextField(verbose_name='Kriterier för icke godkänt')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FormTemplate')),
            ],
        ),
    ]
