# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 20:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Kursnummer')),
                ('year', models.CharField(max_length=32, verbose_name='År')),
                ('term', models.CharField(choices=[('VT', 'Vårtermin'), ('HT', 'Hösttermin')], max_length=2, verbose_name='Termin')),
                ('weeks', models.CharField(max_length=32, verbose_name='Antal veckor VFU')),
            ],
            options={
                'verbose_name': 'kurs',
                'verbose_name_plural': 'kurser',
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_midterm', models.BooleanField(verbose_name='Halvtidssamtal')),
                ('result', models.CharField(choices=[('V', 'Risk för icke godkänt'), ('OK', 'Bra'), ('G', 'Godkänt'), ('VG', 'Väl godkänt'), ('U', 'Icke godkänt')], max_length=3, verbose_name='Resultat')),
            ],
            options={
                'verbose_name': 'formulärssvar',
                'verbose_name_plural': 'formulärssvar',
            },
        ),
        migrations.CreateModel(
            name='FormOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField(help_text='Siffra på fråga, används för sortering och för att lätt kunna referera', verbose_name='Nummer')),
                ('description', models.TextField(verbose_name='Lärandeaspekter')),
                ('done_description', models.TextField(verbose_name='Kriterier för godkänt')),
                ('well_done_description', models.TextField(blank=True, help_text='Behövs endast om formuläret har Väl Godkänt', verbose_name='Kriterier för väl godkänt')),
                ('not_done_description', models.TextField(verbose_name='Kriterier för icke godkänt')),
            ],
            options={
                'verbose_name': 'formulärsfråga',
                'verbose_name_plural': 'formulärsfrågor',
            },
        ),
        migrations.CreateModel(
            name='FormSigningAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titel/befattning')),
                ('name', models.CharField(max_length=256, verbose_name='Namn')),
            ],
            options={
                'verbose_name': 'signerat namn',
                'verbose_name_plural': 'signerade namn',
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Namn')),
                ('has_well_done', models.BooleanField(help_text='Kryssa i det här om du vill att betygskriterier för väl godkänt ska synas och bedömas', verbose_name='Kan betyget väl godkänt ges?')),
                ('applied', models.BooleanField(default=False, verbose_name='Har formuläret applicerats på en kurs?')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='app.Course', verbose_name='Applicerad på kurs')),
            ],
            options={
                'verbose_name': 'formulärsmall',
                'verbose_name_plural': 'formulärsmallar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Namn')),
                ('ssn', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Personnumret måste vara tolv siffror utan bindesstreck (Ex. 197001010000)', regex='^[0-9]{12}$')], verbose_name='Personnummer')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('deleted', models.BooleanField(default=False, verbose_name='Borttagen')),
                ('identity', models.CharField(max_length=64, unique=True, verbose_name='Identitet')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'studenter',
            },
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(blank=True, max_length=256, verbose_name='Handledare/ansvarig')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='VFU-placering')),
                ('midterm_signed', models.BooleanField(default=False, verbose_name='Halvtidsbedömning gjord')),
                ('fullterm_signed', models.BooleanField(default=False, verbose_name='Heltidsbedömning gjord')),
                ('midterm_signed_date', models.DateTimeField(null=True, verbose_name='Datum för halvtidsbedömining')),
                ('fullterm_signed_date', models.DateTimeField(null=True, verbose_name='Datum för heltidsbedömning')),
                ('midterm_comments', models.TextField(blank=True, verbose_name='Kommentarer vid halvtidsbedömning')),
                ('fullterm_comments', models.TextField(blank=True, verbose_name='Kommentarer vid heltidbedömning')),
                ('midterm_absence', models.CharField(blank=True, max_length=10, verbose_name='Frånvaro vid halvtidsbedömning')),
                ('fullterm_absence', models.CharField(blank=True, max_length=10, verbose_name='Frånvaro vid heltidsbedömning')),
                ('fullterm_ok_absence', models.CharField(blank=True, max_length=10, verbose_name='OK Frånvaro vid heltidsbedömning')),
                ('locked', models.BooleanField(default=False, verbose_name='Låst')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_forms', to='app.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FormTemplate')),
            ],
            options={
                'verbose_name': 'studentformulär',
                'verbose_name_plural': 'studentformulär',
            },
        ),
        migrations.AddField(
            model_name='formsigningattendance',
            name='fullterm_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fullterm_user_signed', to='app.StudentForm'),
        ),
        migrations.AddField(
            model_name='formsigningattendance',
            name='midterm_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midterm_user_signed', to='app.StudentForm'),
        ),
        migrations.AddField(
            model_name='formoption',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FormTemplate'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StudentForm'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FormOption'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='app.Student', verbose_name='studenter'),
        ),
    ]
