# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-31 13:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ssn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Personnumret måste vara tolv siffror', regex='^[0-9]{12}$')], verbose_name='Personnummer'),
        ),
    ]
