# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 10:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Namn')),
                ('ssn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator(code='nomatch', message='Personnumret måste vara tolv siffror utan bindesstreck (Ex. 197001010000)', regex='^[0-9]{12}$')], verbose_name='Personnummer')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('deleted', models.BooleanField(default=False, verbose_name='Borttagen')),
                ('identity', models.CharField(db_index=True, max_length=64, verbose_name='Identitet')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical student',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
