# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='fullterm_action_plan',
            field=models.CharField(choices=[('no', 'Behövs ej'), ('yes', 'Åtgärdsplan behöver upprättas'), ('started', 'Åtgärdsplan har upprättats')], default='no', max_length=6, verbose_name='Status för åtgärdsplan vid heltidsbedömning'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='midterm_action_plan',
            field=models.CharField(choices=[('no', 'Behövs ej'), ('yes', 'Åtgärdsplan behöver upprättas'), ('started', 'Åtgärdsplan har upprättats')], default='no', max_length=6, verbose_name='Status för åtgärdsplan vid halvtidsbedömning'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='fullterm_ok_absence',
            field=models.CharField(blank=True, max_length=10, verbose_name='Godkänd frånvaro vid heltidsbedömning'),
        ),
    ]
