# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-02 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='app.Student', verbose_name='studenter'),
        ),
    ]
