# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-31 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='fullterm_absence',
            field=models.CharField(blank=True, max_length=10, verbose_name='Frånvaro vid slutbedömning'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='fullterm_ok_absence',
            field=models.CharField(blank=True, max_length=10, verbose_name='Godkänd frånvaro vid slutbedömning'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='fullterm_signed_date',
            field=models.DateTimeField(null=True, verbose_name='Datum för slutbedömning'),
        ),
    ]
