# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-03 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170803_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='fullterm_action_plan',
        ),
    ]
