# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_historicalstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCourse',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Kursnummer')),
                ('year', models.CharField(max_length=32, verbose_name='År')),
                ('term', models.CharField(choices=[('VT', 'Vårtermin'), ('HT', 'Hösttermin')], max_length=2, verbose_name='Termin')),
                ('weeks', models.CharField(max_length=32, verbose_name='Antal veckor VFU')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical kurs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFormTemplate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Namn')),
                ('has_well_done', models.BooleanField(help_text='Kryssa i det här om du vill att betygskriterier för väl godkänt ska synas och bedömas', verbose_name='Kan betyget väl godkänt ges?')),
                ('applied', models.BooleanField(default=False, verbose_name='Har formuläret applicerats på en kurs?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Course')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical formulärsmall',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudentForm',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('handler', models.CharField(blank=True, max_length=256, verbose_name='Handledare/ansvarig')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='VFU-placering')),
                ('midterm_signed', models.BooleanField(default=False, verbose_name='Halvtidsbedömning gjord')),
                ('fullterm_signed', models.BooleanField(default=False, verbose_name='Heltidsbedömning gjord')),
                ('midterm_signed_date', models.DateTimeField(null=True, verbose_name='Datum för halvtidsbedömining')),
                ('fullterm_signed_date', models.DateTimeField(null=True, verbose_name='Datum för heltidsbedömning')),
                ('midterm_comments', models.TextField(blank=True, verbose_name='Kommentarer vid halvtidsbedömning')),
                ('fullterm_comments', models.TextField(blank=True, verbose_name='Kommentarer vid heltidbedömning')),
                ('midterm_absence', models.CharField(blank=True, max_length=10, verbose_name='Frånvaro vid halvtidsbedömning')),
                ('fullterm_absence', models.CharField(blank=True, max_length=10, verbose_name='Frånvaro vid heltidsbedömning')),
                ('fullterm_ok_absence', models.CharField(blank=True, max_length=10, verbose_name='OK Frånvaro vid heltidsbedömning')),
                ('locked', models.BooleanField(default=False, verbose_name='Låst')),
                ('link_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Read only länk id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Course')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Student')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.FormTemplate')),
            ],
            options={
                'verbose_name': 'historical studentformulär',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
