# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161223_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_midterm', models.BooleanField(verbose_name='Halvtidssamtal')),
                ('result', models.CharField(choices=[('G', 'Godkänt'), ('VG', 'Väl godkänt'), ('U', 'Icke godkänt')], max_length=3, verbose_name='Resultat')),
            ],
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
        migrations.RenameField(
            model_name='templateoption',
            old_name='doneDescription',
            new_name='done_description',
        ),
        migrations.RenameField(
            model_name='templateoption',
            old_name='notDoneDescription',
            new_name='not_done_description',
        ),
        migrations.RenameField(
            model_name='templateoption',
            old_name='wellDoneDescription',
            new_name='well_done_description',
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='has_well_done',
            field=models.BooleanField(default=True, verbose_name='Kan betyget väl godkänt ges?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FormTemplate'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StudentForm'),
        ),
    ]
