# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161224_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
