# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_historicalcourse_historicalformtemplate_historicalstudentform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('can_view_app_courses', 'Lista kurser i appvyn'), ('can_view_app_course', 'Lista kurs i appvyn')), 'verbose_name': 'kurs', 'verbose_name_plural': 'kurser'},
        ),
        migrations.AlterModelOptions(
            name='studentform',
            options={'permissions': (('can_view_app_student_form', 'Visa studentformulär'),), 'verbose_name': 'studentformulär', 'verbose_name_plural': 'studentformulär'},
        ),
    ]
