# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_studentform_fullterm_action_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='', verbose_name='Beskrivning av kursen, generella mål'),
        ),
    ]
