# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161224_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='students',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('VT', 'Vårtermin'), ('HT', 'Hösttermin')], default="HT", max_length=2, verbose_name='Termin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formanswer',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.TemplateOption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Borttagen'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='location',
            field=models.CharField(default='', max_length=256, verbose_name='VFU-placering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='weeks',
            field=models.CharField(max_length=32, verbose_name='Antal veckor VFU'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='result',
            field=models.CharField(choices=[('V', 'Risk för icke godkänt'), ('OK', 'Bra'), ('G', 'Godkänt'), ('VG', 'Väl godkänt'), ('U', 'Icke godkänt')], max_length=3, verbose_name='Resultat'),
        ),
        migrations.DeleteModel(
            name='CourseGroup',
        ),
    ]
