# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170913_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_add_multiple_app_student', 'Importera flera studenter från admin panelen'),), 'verbose_name': 'student', 'verbose_name_plural': 'studenter'},
        ),
        migrations.AlterModelOptions(
            name='studentform',
            options={'permissions': (('can_view_app_student_form', 'Visa studentformulär'), ('can_view_app_student_action_plan', 'Visa åtgärdsplan')), 'verbose_name': 'studentformulär', 'verbose_name_plural': 'studentformulär'},
        ),
    ]
