# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170405_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSigningAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titel/befattning')),
                ('name', models.CharField(max_length=256, verbose_name='Namn')),
                ('midterm_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_signed', to='app.StudentForm')),
                ('term_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_signed', to='app.StudentForm')),
            ],
        ),
        migrations.RenameModel(
            old_name='TemplateOption',
            new_name='FormOption',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='app.Student'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='Har formuläret applicerats på en kurs?'),
            preserve_default=False,
        ),
    ]
