# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170411_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'kurs', 'verbose_name_plural': 'kurser'},
        ),
        migrations.AlterModelOptions(
            name='formanswer',
            options={'verbose_name': 'formulärssvar', 'verbose_name_plural': 'formulärssvar'},
        ),
        migrations.AlterModelOptions(
            name='formoption',
            options={'verbose_name': 'formulärsfråga', 'verbose_name_plural': 'formulärsfrågor'},
        ),
        migrations.AlterModelOptions(
            name='formsigningattendance',
            options={'verbose_name': 'signerat namn', 'verbose_name_plural': 'signerade namn'},
        ),
        migrations.AlterModelOptions(
            name='formtemplate',
            options={'verbose_name': 'formulärsmall', 'verbose_name_plural': 'formulärsmallar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'studenter'},
        ),
        migrations.AlterModelOptions(
            name='studentform',
            options={'verbose_name': 'studentformulär', 'verbose_name_plural': 'studentformulär'},
        ),
        migrations.AlterField(
            model_name='formoption',
            name='well_done_description',
            field=models.TextField(blank=True, help_text='Behövs endast om formuläret har Väl Godkänt', verbose_name='Kriterier för väl godkänt'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='Har formuläret applicerats på en kurs?'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Namn'),
        ),
    ]
