# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170417_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Course', verbose_name='Applicerad på kurs'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='has_well_done',
            field=models.BooleanField(help_text='Kryssa i det här om du vill att betygskriterier för väl godkänt ska synas och bedömas', verbose_name='Kan betyget väl godkänt ges?'),
        ),
    ]
