# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170417_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='app.Student', verbose_name='studenter'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_template', to='app.Course', verbose_name='Applicerad på kurs'),
        ),
    ]
