# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170417_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_forms', to='app.Course'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='fullterm_signed',
            field=models.BooleanField(default=False, verbose_name='Heltidsbedömning gjord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Låst'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='midterm_signed',
            field=models.BooleanField(default=False, verbose_name='Halvtidsbedömning gjord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formsigningattendance',
            name='midterm_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_user_signed', to='app.StudentForm'),
        ),
        migrations.AlterField(
            model_name='formsigningattendance',
            name='term_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullterm_user_signed', to='app.StudentForm'),
        ),
    ]
