# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170423_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='formoption',
            name='nr',
            field=models.IntegerField(default=1, help_text='Siffra på fråga, används för sortering och för att lätt kunna referera', verbose_name='Nummer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='app.Course', verbose_name='Applicerad på kurs'),
        ),
    ]
