# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-11 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170508_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='fullterm_signed',
            field=models.BooleanField(default=False, verbose_name='Heltidsbedömning gjord'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='location',
            field=models.CharField(blank=True, max_length=256, verbose_name='VFU-placering'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Låst'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='midterm_signed',
            field=models.BooleanField(default=False, verbose_name='Halvtidsbedömning gjord'),
        ),
    ]
