# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170511_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='johan@re3-labs.net', max_length=254, verbose_name='Email'),
        ),
    ]
