# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170621_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='handler',
            field=models.CharField(blank=True, max_length=256, verbose_name='Handledare/ansvarig'),
        ),
    ]
