# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-02 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170621_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssn',
            field=models.CharField(max_length=18, unique=True, verbose_name='Personnummer'),
        ),
    ]
