# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_studentform_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='fullterm_absence',
            field=models.CharField(blank=True, max_length=10, verbose_name='Frånvaro vid heltidsbedömning'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='fullterm_comments',
            field=models.TextField(blank=True, verbose_name='Kommentarer vid heltidbedömning'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='fullterm_ok_absence',
            field=models.CharField(blank=True, max_length=10, verbose_name='OK Frånvaro vid heltidsbedömning'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='midterm_absence',
            field=models.CharField(blank=True, max_length=10, verbose_name='Frånvaro vid halvtidsbedömning'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='midterm_comments',
            field=models.TextField(blank=True, verbose_name='Kommentarer vid halvtidsbedömning'),
        ),
    ]
