# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170801_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsigningattendance',
            name='term_sign',
        ),
        migrations.AddField(
            model_name='formsigningattendance',
            name='fullterm_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fullterm_user_signed', to='app.StudentForm'),
        ),
        migrations.AlterField(
            model_name='formsigningattendance',
            name='midterm_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midterm_user_signed', to='app.StudentForm'),
        ),
    ]
