# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170801_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='fullterm_signed_date',
            field=models.DateTimeField(null=True, verbose_name='Datum för heltidsbedömning'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='midterm_signed_date',
            field=models.DateTimeField(null=True, verbose_name='Datum för halvtidsbedömining'),
        ),
    ]
